# The west manifest file (west.yml) importing the nRF Connect SDK (NCS).

manifest:
  version: "0.10"

  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/tejlmand

  # If not otherwise specified, the projects below should be obtained
  # from the ncs remote.
  defaults:
    remote: ncs

  # "projects" is a list of git repositories which make up the NCS
  # source code.
  projects:

    - name: nrf
      repo-path: fw-nrfconnect-nrf
      revision: 004f28919197ab0de0dcc2b4538568cb3a94c249
      import: true

  self:
    path: multi_manifest_repo/nRF_connect_SDK
